### PR TITLE
added Scopes section within url-dispatch 

### PR DESCRIPTION
**Pull request by Dowwie**

### CODE REVIEW

**Comment by fafhrd91** [comment]
let's wait a bit. especially on trailing slash.

**Comment by fafhrd91** [comment]
I need you to test your code. 
rules are:

## 1.
  scope: /app
  resource1: ""
  resource2: "/"

  /app - resource1
  /app/ - resource2

## 2.
  scope: /app/
  resource1: ""

  /app - not found
  /app/ - resource1

## 3.
  scope: /app/
  resource1: "/"

  /app - not found
  /app/ - not found

**Comment by fafhrd91** [comment]
could you also update your pr for scope docs

**Comment by Dowwie** [comment]
I have no idea what you're asking me to do..

**Comment by fafhrd91** [comment]
looks good!

**Pull request merged**
