### PR TITLE
Errors: split code lines to make where logger is wrapped clearer.

### PR DESCRIPTION
**Pull request by nabbisen**

### CODE REVIEW

**Review by robjtede — APPROVED** [review]
Trouble with this these is rustfmt puts it back if we ever run it on the repo. Might be worth adding a rustfmt::skip somewhere. I'll merge this later on if you want to add it.

**Comment by fakeshadow** [comment]
```rust
let logger = Logger::default();
App::new().wrap(logger)
```

**Comment by nabbisen** [comment]
I didn't know `cargo fmt` converts this way. Sorry:

```diff
- App::new()
-     .wrap(logger)
-     .service(index)
+ App::new().wrap(logger).service(index)
```

**Comment by robjtede** [comment]
What you did is clearer though.

**Comment by nabbisen** [comment]
> What you did is clearer though.

Thanks. I'll use rustfmt::skip.

**Comment by nabbisen** [comment]
> What you did is clearer though.

Thanks. I'll use rustfmt::skip.

**Pull request closed without merging**
